## Импорт библиотек

In [1]:
import pandas as pd 
import numpy as np

## Чтение csv файла и первичный осмотр данных

In [2]:
df = pd.read_csv("../data/raw/uniprot_human_swissprot_raw.tsv", sep="\t")
df.head(5)

,Entry,Entry Name,Protein names,Gene Names,Organism,Length,Sequence,Subcellular location [CC]
0,A0A087X1C5,CP2D7_HUMAN,Cytochrome P450 2D7 (EC 1.14.14.1),CYP2D7,Homo sapiens (Human),515,MGLEALVPLAMIVAIFLLLVDLMHRHQRWAARYPPGPLPLPGLGNL...,SUBCELLULAR LOCATION: Membrane {ECO:0000305}; ...
1,A0A096LP01,SIM26_HUMAN,Small integral membrane protein 26,SMIM26 LINC00493,Homo sapiens (Human),95,MYRNEFTAWYRRMSVVYGIGTWSVLGSLLYYSRTMAKSSVDQKDGS...,SUBCELLULAR LOCATION: Mitochondrion outer memb...
2,A0A0B4J2F0,PIOS1_HUMAN,Protein PIGBOS1 (PIGB opposite strand protein 1),PIGBOS1,Homo sapiens (Human),54,MFRRLTFAQLLFATVLGIAGGVYIFQPVFEQYAKDQKELKEKMQLV...,SUBCELLULAR LOCATION: Mitochondrion outer memb...
3,A0A0C5B5G6,MOTSC_HUMAN,Mitochondrial-derived peptide MOTS-c (Mitochon...,MT-RNR1,Homo sapiens (Human),16,MRWQEMGYIFYPRKLR,SUBCELLULAR LOCATION: Secreted {ECO:0000269|Pu...
4,A0A0K2S4Q6,CD3CH_HUMAN,Protein CD300H (CD300 antigen-like family memb...,CD300H,Homo sapiens (Human),201,MTQRAGAAMLPSALLLLCVPGCLTVSGPSTVMGAVGESLSVQCRYE...,SUBCELLULAR LOCATION: [Isoform 1]: Membrane {E...

In [3]:
df.columns.tolist()

['Entry',
 'Entry Name',
 'Protein names',
 'Gene Names',
 'Organism',
 'Length',
 'Sequence',
 'Subcellular location [CC]']

Значение столбцов:
- Entry: Уникальный идентификатор записи
- Entry Name: Краткое имя записи
- Protein names: Названия белка
- Gene Names: Названия генов
- Organism: Организм
- Length: Длина последовательности
- Sequence: Аминокислотная последовательность
- Subcellular location [CC]: Текст аннотации локализации

In [4]:
print(f"Размер dataframe: {df.shape}")

Размер dataframe: (17342, 8)

In [5]:
# Проверка info:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17342 entries, 0 to 17341
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Entry                      17342 non-null  str
 1   Entry Name                 17342 non-null  str
 2   Protein names              17342 non-null  str
 3   Gene Names                 17320 non-null  str
 4   Organism                   17342 non-null  str
 5   Length                     17342 non-null  int64
 6   Sequence                   17342 non-null  str
 7   Subcellular location [CC]  17342 non-null  str
dtypes: int64(1), str(7)
memory usage: 1.1 MB

In [6]:
# Проверка пропусков
df.isna().sum()

Entry                         0
Entry Name                    0
Protein names                 0
Gene Names                   22
Organism                      0
Length                        0
Sequence                      0
Subcellular location [CC]     0
dtype: int64

Пропуски найдены только в столбце Gene Names

In [7]:
df.describe()

             Length
count  17342.000000
mean     581.856533
std      635.439120
min        2.000000
25%      270.000000
50%      428.000000
75%      693.000000
max    34350.000000

In [8]:
# Проверка дубликатов
df.duplicated().sum()

np.int64(0)

In [9]:
# Проверка уникальных значений
df.nunique()

Entry                        17342
Entry Name                   17342
Protein names                17342
Gene Names                   17284
Organism                         1
Length                        2111
Sequence                     17303
Subcellular location [CC]    12209
dtype: int64

In [ ]:
# Пример и проверка источника будущей целевой метки
pd.set_option("display.max_colwidth", None)
df["Subcellular location [CC]"].head()

0                                                                                                                                 SUBCELLULAR LOCATION: Membrane {ECO:0000305}; Multi-pass membrane protein {ECO:0000255}. Cytoplasm {ECO:0000305|PubMed:15051713}. Mitochondrion {ECO:0000269|PubMed:18838503}.
1                                                                                                                                                     SUBCELLULAR LOCATION: Mitochondrion outer membrane {ECO:0000269|PubMed:33386847, ECO:0000269|PubMed:37009826}; Single-pass membrane protein {ECO:0000255}.
2                                                                                                                                                                                  SUBCELLULAR LOCATION: Mitochondrion outer membrane {ECO:0000269|PubMed:31653868}; Single-pass membrane protein {ECO:0000255}.
3    SUBCELLULAR LOCATION: Secreted {ECO:0000269|PubMed:25738459}. Mitochondrion {ECO:0000269|PubMed:29983246}. Nucleus {ECO:0000269|PubMed:29983246, ECO:0000269|PubMed:33473109}. Note=Translocates to the nucleus in response to metabolic stress in an AMPK-dependent manner. {ECO:0000269|PubMed:29983246}.
4                                                                                                                      SUBCELLULAR LOCATION: [Isoform 1]: Membrane {ECO:0000255}; Single-pass type I membrane protein {ECO:0000255}.; SUBCELLULAR LOCATION: [Isoform 2]: Secreted {ECO:0000269|PubMed:26221034}.
Name: Subcellular location [CC], dtype: str